num1 = int(input())
num2 = int(input())
num3 = int(input())
maxnum = max(num1, num2, num3)
minnum = min(num1, num2, num3)
razn = (num1 +num2 +num3) - max(num1, num2, num3) - min(num1, num2, num3)
print (maxnum, razn, minnum, sep='\n')